
server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /demo-web

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.15:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: nsn
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      max-wait: 60000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20


mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:user-mapper/*.xml
  type-aliases-package: com.nsn.demo.dal.po
